name: LumenMail
version: 1.0 alpha
author: Pangamma
website: http://LumenGaming.com
main: com.lumengaming.lumenmail.LumenMail
description: A mail system built to work on Pangamma's personal server.
commands:
  lumenmail:
    description: Main command.
    aliases: ['mail']